/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dopm_mm2.GUI;

import java.util.logging.Logger;
import javax.swing.*;
import org.micromanager.Studio;
import mmcorej.CMMCore;
import org.micromanager.ScriptController;
import org.micromanager.data.Datastore;
import dopm_mm2.Devices.DeviceManager;
import dopm_mm2.Runnables.PIScanRunnable;
import dopm_mm2.Runnables.PIScanRunnableInherited;
import dopm_mm2.Runnables.snapGeneralVolumeRunnable;
import dopm_mm2.util.MMStudioInstance;
import java.io.File;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.logging.FileHandler;
import java.util.logging.SimpleFormatter;
import org.micromanager.acquisition.ChannelSpec;

/**
 *
 * @author lnr19
 */
public class dOPM_hostframe extends javax.swing.JFrame {

    static dOPM_hostframe frame_;
    public static Studio mm_ = null;
    public CMMCore core_ = null;
    private static final Logger dOPM_hostframeLogger = 
            Logger.getLogger(dOPM_hostframe.class.getName());
    
    // TODO: save this to a file
    private static final Logger rootLogger = 
        Logger.getLogger("");
    private File dopm_mm2Logdir;
    private File dopm_mm2Logfile;
    
    public Thread testPIVolumeThread;
    private boolean interruptFlag;
    private Datastore datastore;
    
    // Base folder directory and other directories
    private File baseFolderDir;
    private File settingsFolderDir;
    private File dataFolderDir;
    
    private File defaultConfigFile;
    
    private boolean saveImgToDisk;
    private boolean runnableIsRunning;
    
    // Device settings object
    DeviceManager deviceSettings;    

    //Other settings ?
    // ...
    
    //Various managers
    private ScriptController sc;
    
    public dOPM_hostframe() {
        makeDirsAndLog();
        initComponents();
    }

    public dOPM_hostframe(Studio mm) {        
        // singleton which contains studio and core so i dont have to inject every time
        MMStudioInstance.initialize(mm);
        mm_ = mm;
        core_ = MMStudioInstance.getCore();

        frame_ = this;
        frame_.setTitle("dOPM controller for Micro-manager 2");
        frame_.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                
        saveImgToDisk = false;
        baseFolderDir = new File("C:\\Users\\CRICKOPMuser\\Documents\\Leo\\micromanager");
        dataFolderDir = new File(baseFolderDir, "data");
        settingsFolderDir = new File(baseFolderDir, "settings");
        
        defaultConfigFile = new File("C:\\Users\\CRICKOPMuser\\Documents\\" + 
                "Leo\\micromanager\\dopm_plugin\\defaultDeviceConfig.csv").getAbsoluteFile();
                
        deviceSettings = new DeviceManager(core_);
        deviceSettings.loadDeviceNames(defaultConfigFile);
        
        runnableIsRunning = false;
        
        makeDirsAndLog();
        initComponents();
        
        dOPM_hostframeLogger.info("Initialised dOPM_MM2 hostframe");

    }
    
    private int makeDirsAndLog(){
        try { 
            LocalDateTime date = LocalDateTime.now(); // Create a date object
            DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern(
                    "yyyyMMddhhmmss");

            String formattedDate = date.format(myFormatObj);
            
            String appdata = System.getenv("APPDATA");
            dopm_mm2Logdir = new File(appdata, "../Local/Micro-Manager/dopmLogs");
            dopm_mm2Logdir.mkdir();
            dopm_mm2Logfile = new File(dopm_mm2Logdir, String.format(
                    "dopmRootLog%s.log", formattedDate));
            
            FileHandler fh = new FileHandler(dopm_mm2Logfile.getAbsolutePath());
 
            rootLogger.addHandler(fh);
            SimpleFormatter formatter = new SimpleFormatter();  
            fh.setFormatter(formatter);  
        } catch (IOException ioe){
            rootLogger.severe("Failed to create log with " + ioe.getMessage());
            return 1;
        } catch (SecurityException se){
            rootLogger.severe("Failed to create log file " + se.getMessage());
            return 1;
        }
        return 0;
    }
        
    private Object[] getLaserChannelOptions() throws Exception{
        throw new Exception("Not implemented");
    }
    
    private void getPossibleDeviceStates(){
        // TODO delete
    }
    
    private void openDeviceConfig(){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fileSettingsPanel = new javax.swing.JPanel();
        saveDirectoryLabel = new javax.swing.JLabel();
        saveDirectoryField = new javax.swing.JTextField();
        browseDirectoryField = new javax.swing.JButton();
        saveToDiskCheckBox = new javax.swing.JCheckBox();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        debugTextArea = new javax.swing.JTextArea();
        jProgressBar = new javax.swing.JProgressBar();
        snapTestButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        mirrorScanSettingsPanel = new javax.swing.JPanel();
        mirrorScanLengthField = new javax.swing.JTextField();
        mirrorScanSpeedField = new javax.swing.JTextField();
        mirrorScanIntervalField = new javax.swing.JTextField();
        mirrorMaxSpeedCheckBox = new javax.swing.JCheckBox();
        pcOfMaxField1 = new javax.swing.JTextField();
        pcOfMaxLabel1 = new javax.swing.JLabel();
        scanLengthLabel1 = new javax.swing.JLabel();
        scanSpeedLabel1 = new javax.swing.JLabel();
        scanIntervalLabel1 = new javax.swing.JLabel();
        xyStageScanSettingsPanel = new javax.swing.JPanel();
        xyScanLengthField = new javax.swing.JTextField();
        xyScanSpeedField = new javax.swing.JTextField();
        xyScanIntervalField = new javax.swing.JTextField();
        xyMaxSpeedCheckBox = new javax.swing.JCheckBox();
        scanLengthLabel = new javax.swing.JLabel();
        scanSpeedLabel = new javax.swing.JLabel();
        scanIntervalLabel = new javax.swing.JLabel();
        pcOfMaxLabel = new javax.swing.JLabel();
        pcOfMaxField = new javax.swing.JTextField();
        triggerModeLabel = new javax.swing.JLabel();
        triggerModeComboBox = new javax.swing.JComboBox<>();
        mirrorScanRadioButton = new javax.swing.JRadioButton();
        xScanRadioButton = new javax.swing.JRadioButton();
        yScanRadioButton = new javax.swing.JRadioButton();
        scanStageTypeLabel = new javax.swing.JLabel();
        viewsLabel = new javax.swing.JLabel();
        view1CheckBox = new javax.swing.JCheckBox();
        view2CheckBox = new javax.swing.JCheckBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openDeviceConfigMenuItem = new javax.swing.JMenuItem();
        clearLogsMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileSettingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("File settings"));

        saveDirectoryLabel.setText("Save directory");

        saveDirectoryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDirectoryFieldActionPerformed(evt);
            }
        });

        browseDirectoryField.setText("Browse");
        browseDirectoryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseDirectoryFieldActionPerformed(evt);
            }
        });

        saveToDiskCheckBox.setText("Save to disk");
        saveToDiskCheckBox.setAlignmentX(1.0F);
        saveToDiskCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        saveToDiskCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        saveToDiskCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveToDiskCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fileSettingsPanelLayout = new javax.swing.GroupLayout(fileSettingsPanel);
        fileSettingsPanel.setLayout(fileSettingsPanelLayout);
        fileSettingsPanelLayout.setHorizontalGroup(
            fileSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileSettingsPanelLayout.createSequentialGroup()
                .addGroup(fileSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fileSettingsPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(saveDirectoryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveDirectoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseDirectoryField))
                    .addGroup(fileSettingsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(saveToDiskCheckBox)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fileSettingsPanelLayout.setVerticalGroup(
            fileSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileSettingsPanelLayout.createSequentialGroup()
                .addGroup(fileSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveDirectoryLabel)
                    .addComponent(saveDirectoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseDirectoryField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveToDiskCheckBox)
                .addContainerGap())
        );

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        debugTextArea.setEditable(false);
        debugTextArea.setColumns(20);
        debugTextArea.setRows(5);
        jScrollPane1.setViewportView(debugTextArea);

        snapTestButton.setText("snap test");
        snapTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snapTestButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Scan settings"));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTabbedPane1.setName("Mirror scan"); // NOI18N

        mirrorScanSettingsPanel.setPreferredSize(new java.awt.Dimension(380, 96));

        mirrorScanLengthField.setText(String.format("%.1f", deviceSettings.getMirrorScanLength()));
        mirrorScanLengthField.setInputVerifier(new typeVerifierDouble());
        mirrorScanLengthField.setPreferredSize(new java.awt.Dimension(100, 22));
        mirrorScanLengthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mirrorScanLengthFieldActionPerformed(evt);
            }
        });

        mirrorScanSpeedField.setText(String.format("%.4f", deviceSettings.getMirrorStageGlobalScanSpeed()));
        mirrorScanSpeedField.setActionCommand("<Not Set>");
        mirrorScanSpeedField.setInputVerifier(new typeVerifierDouble());
        mirrorScanSpeedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mirrorScanSpeedFieldActionPerformed(evt);
            }
        });

        mirrorScanIntervalField.setText(String.format("%.2f", deviceSettings.getMirrorTriggerDistance()));
        mirrorScanIntervalField.setInputVerifier(new typeVerifierDouble());
        mirrorScanIntervalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mirrorScanIntervalFieldActionPerformed(evt);
            }
        });

        mirrorMaxSpeedCheckBox.setText("Max");
        mirrorMaxSpeedCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        mirrorMaxSpeedCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mirrorMaxSpeedCheckBoxActionPerformed(evt);
            }
        });

        pcOfMaxField1.setText(String.format("%.2f",deviceSettings.getScanSpeedSafetyFactor()));

        pcOfMaxLabel1.setText("% of Max");

        scanLengthLabel1.setText("Scan length (µm)");

        scanSpeedLabel1.setText("Scan speed (µm/ms)");

        scanIntervalLabel1.setText("Scan interval (µm)");

        javax.swing.GroupLayout mirrorScanSettingsPanelLayout = new javax.swing.GroupLayout(mirrorScanSettingsPanel);
        mirrorScanSettingsPanel.setLayout(mirrorScanSettingsPanelLayout);
        mirrorScanSettingsPanelLayout.setHorizontalGroup(
            mirrorScanSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mirrorScanSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mirrorScanSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scanLengthLabel1)
                    .addComponent(scanSpeedLabel1)
                    .addComponent(scanIntervalLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mirrorScanSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mirrorScanIntervalField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mirrorScanSettingsPanelLayout.createSequentialGroup()
                        .addComponent(mirrorScanSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mirrorMaxSpeedCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pcOfMaxLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pcOfMaxField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mirrorScanLengthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mirrorScanSettingsPanelLayout.setVerticalGroup(
            mirrorScanSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mirrorScanSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mirrorScanSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mirrorScanLengthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scanLengthLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mirrorScanSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mirrorMaxSpeedCheckBox)
                    .addComponent(mirrorScanSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcOfMaxField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcOfMaxLabel1)
                    .addComponent(scanSpeedLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mirrorScanSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scanIntervalLabel1)
                    .addComponent(mirrorScanIntervalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mirror scan", mirrorScanSettingsPanel);

        xyScanLengthField.setText(String.format("%.1f", deviceSettings.getXyStageScanLength()));
        xyScanLengthField.setInputVerifier(new typeVerifierDouble());
        xyScanLengthField.setPreferredSize(new java.awt.Dimension(100, 22));
        xyScanLengthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xyScanLengthFieldActionPerformed(evt);
            }
        });

        xyScanSpeedField.setText(String.format("%.4f", deviceSettings.getXyStageCurrentScanSpeed()));
        xyScanSpeedField.setActionCommand("<Not Set>");
        xyScanSpeedField.setInputVerifier(new typeVerifierDouble());
        xyScanSpeedField.setPreferredSize(new java.awt.Dimension(100, 22));
        xyScanSpeedField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xyScanSpeedFieldActionPerformed(evt);
            }
        });

        xyScanIntervalField.setText(String.format("%.2f", deviceSettings.getXyStageTriggerDistance()));
        xyScanIntervalField.setInputVerifier(new typeVerifierDouble());
        xyScanIntervalField.setPreferredSize(new java.awt.Dimension(100, 22));
        xyScanIntervalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xyScanIntervalFieldActionPerformed(evt);
            }
        });

        xyMaxSpeedCheckBox.setText("Max");
        xyMaxSpeedCheckBox.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        xyMaxSpeedCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xyMaxSpeedCheckBoxActionPerformed(evt);
            }
        });

        scanLengthLabel.setText("Scan length (µm)");

        scanSpeedLabel.setText("Scan speed (µm/ms)");

        scanIntervalLabel.setText("Scan interval (µm)");

        pcOfMaxLabel.setText("% of Max");

        pcOfMaxField.setText(String.format("%.2f",deviceSettings.getScanSpeedSafetyFactor()));

        javax.swing.GroupLayout xyStageScanSettingsPanelLayout = new javax.swing.GroupLayout(xyStageScanSettingsPanel);
        xyStageScanSettingsPanel.setLayout(xyStageScanSettingsPanelLayout);
        xyStageScanSettingsPanelLayout.setHorizontalGroup(
            xyStageScanSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xyStageScanSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xyStageScanSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scanSpeedLabel)
                    .addComponent(scanIntervalLabel)
                    .addComponent(scanLengthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(xyStageScanSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(xyStageScanSettingsPanelLayout.createSequentialGroup()
                        .addGroup(xyStageScanSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(xyStageScanSettingsPanelLayout.createSequentialGroup()
                                .addComponent(xyScanSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xyMaxSpeedCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pcOfMaxLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pcOfMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(xyScanLengthField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(xyStageScanSettingsPanelLayout.createSequentialGroup()
                        .addComponent(xyScanIntervalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        xyStageScanSettingsPanelLayout.setVerticalGroup(
            xyStageScanSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xyStageScanSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(xyStageScanSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xyScanLengthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scanLengthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(xyStageScanSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xyMaxSpeedCheckBox)
                    .addComponent(xyScanSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scanSpeedLabel)
                    .addComponent(pcOfMaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pcOfMaxLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(xyStageScanSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xyScanIntervalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scanIntervalLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("XY Stage scan", xyStageScanSettingsPanel);

        triggerModeLabel.setText("Trigger mode");

        triggerModeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "External trigger (global reset)", "External trigger (global exposure with rolling)", "Untriggered" }));
        triggerModeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triggerModeComboBoxActionPerformed(evt);
            }
        });

        buttonGroup1.add(mirrorScanRadioButton);
        mirrorScanRadioButton.setSelected(true);
        mirrorScanRadioButton.setText("Mirror");
        mirrorScanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mirrorScanRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(xScanRadioButton);
        xScanRadioButton.setText("X stage");
        xScanRadioButton.setToolTipText("Unused, X scan is unlikely to be used");
        xScanRadioButton.setEnabled(false);
        xScanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xScanRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(yScanRadioButton);
        yScanRadioButton.setText("Y Stage");
        yScanRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        yScanRadioButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        yScanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yScanRadioButtonActionPerformed(evt);
            }
        });

        scanStageTypeLabel.setText("Scan type");

        viewsLabel.setText("Views acquired");

        view1CheckBox.setSelected(deviceSettings.isView1Imaged());
        view1CheckBox.setText("View 1");
        view1CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view1CheckBoxActionPerformed(evt);
            }
        });

        view2CheckBox.setSelected(deviceSettings.isView2Imaged());
        view2CheckBox.setText("View 2");
        view2CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view2CheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scanStageTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(triggerModeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(triggerModeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mirrorScanRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yScanRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xScanRadioButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(view1CheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(view2CheckBox))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(triggerModeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(triggerModeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mirrorScanRadioButton)
                    .addComponent(scanStageTypeLabel)
                    .addComponent(yScanRadioButton)
                    .addComponent(xScanRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(viewsLabel)
                        .addComponent(view1CheckBox))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(view2CheckBox)
                        .addContainerGap())))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Mirror scan");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        jMenu1.setText("File");

        openDeviceConfigMenuItem.setText("Open Device Config");
        openDeviceConfigMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openDeviceConfigMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(openDeviceConfigMenuItem);

        clearLogsMenuItem.setText("Clear dOPM logs");
        clearLogsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearLogsMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(clearLogsMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startButton)
                            .addComponent(stopButton)
                            .addComponent(snapTestButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fileSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileSettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(startButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stopButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(snapTestButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    
    private void triggerModeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triggerModeComboBoxActionPerformed
        deviceSettings.setTriggerMode(triggerModeComboBox.getSelectedIndex());
        // update the max triggered scan speed since it is affected by triggerMode
    }//GEN-LAST:event_triggerModeComboBoxActionPerformed

    private void browseDirectoryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseDirectoryFieldActionPerformed
        JFileChooser fc = new JFileChooser(baseFolderDir);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showDialog(this, "Select");
        
        if (returnVal == JFileChooser.APPROVE_OPTION){
            baseFolderDir = fc.getSelectedFile();
            saveDirectoryField.setText(baseFolderDir.getAbsolutePath());
            setDataFolderDir(new File(baseFolderDir, "data"));
        }
    }//GEN-LAST:event_browseDirectoryFieldActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        if(runnableIsRunning) this.setInterruptFlag(true);
        else this.setInterruptFlag(false);
    }//GEN-LAST:event_stopButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // run the runnable        
        int scanType = deviceSettings.getScanType();
        
        // Method that uses the MDA sequencer: // // // // // // // // // // //
        Runnable volumeAcqRunnable = new snapGeneralVolumeRunnable(this, scanType);
        Thread volumeAcqThread = new Thread(volumeAcqRunnable);
        volumeAcqThread.start();
        setRunnableIsRunning(true);
        
        // Does this do anything now that we pass runnable to acquisitions()?
        /*
        Thread mirrorScanRunnableThread = new Thread(mirrorScanRunnable);
            mirrorScanRunnableThread.setUncaughtExceptionHandler(
                    new Thread.UncaughtExceptionHandler() {
            @Override
            public void uncaughtException(Thread t, Throwable e) {
                // Handle the uncaught exception here (e.g., log it, alert users, etc.)
                dOPM_hostframeLogger.severe("Exception in thread " + t.getName() 
                        + ": " + e.getMessage());
            }
        });*/
    }//GEN-LAST:event_startButtonActionPerformed

    private void saveToDiskCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToDiskCheckBoxActionPerformed
        if (saveToDiskCheckBox.isSelected()){
            setSaveImgToDisk(true);
        } else {
            setSaveImgToDisk(false);
        }
    }//GEN-LAST:event_saveToDiskCheckBoxActionPerformed

    
    private void saveDirectoryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDirectoryFieldActionPerformed
        setBaseFolderDir(new File(saveDirectoryField.getText()));
    }//GEN-LAST:event_saveDirectoryFieldActionPerformed

    private void snapTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snapTestButtonActionPerformed
        // Runnable testRunnable = new PITriggerTest(core_, mm_);
        // Runnable testRunnable = new snapGeneralVolumeRunnable(this, "null");
        // mm_.getAcquisitionManager().attachRunnable(-1, -1, -1, -1, testRunnable);
        // mm_.getAcquisitionManager().runAcquisitionNonblocking();
        // Thread testThread = new Thread(testRunnable);
        // testThread.start();
    }//GEN-LAST:event_snapTestButtonActionPerformed

    private void openDeviceConfigMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openDeviceConfigMenuItemActionPerformed
        JFileChooser fc = new JFileChooser(baseFolderDir);
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = fc.showDialog(this, "Select");

        if (returnVal == JFileChooser.APPROVE_OPTION){
            File configFile = fc.getSelectedFile();
            setDefaultConfigFile(configFile);
            deviceSettings.loadDeviceNames(configFile);
        }   
    }//GEN-LAST:event_openDeviceConfigMenuItemActionPerformed


    private void mirrorScanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mirrorScanRadioButtonActionPerformed
        if (mirrorScanRadioButton.isSelected()){
            deviceSettings.setScanType(DeviceManager.MIRROR_SCAN);
        }
    }//GEN-LAST:event_mirrorScanRadioButtonActionPerformed

    private void xScanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xScanRadioButtonActionPerformed
        if (xScanRadioButton.isSelected()){
            deviceSettings.setScanType(DeviceManager.XSTAGE_SCAN);
        }
    }//GEN-LAST:event_xScanRadioButtonActionPerformed

    private void yScanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yScanRadioButtonActionPerformed
        if (yScanRadioButton.isSelected()){
            deviceSettings.setScanType(DeviceManager.YSTAGE_SCAN);
        }
    }//GEN-LAST:event_yScanRadioButtonActionPerformed

    private void view2CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view2CheckBoxActionPerformed
        if (mirrorMaxSpeedCheckBox.isSelected()){
            deviceSettings.setView2Imaged(true);
        } else deviceSettings.setView2Imaged(false);
    }//GEN-LAST:event_view2CheckBoxActionPerformed

    private void view1CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view1CheckBoxActionPerformed
        if (mirrorMaxSpeedCheckBox.isSelected()){
            deviceSettings.setView1Imaged(true);
        } else deviceSettings.setView1Imaged(false);
    }//GEN-LAST:event_view1CheckBoxActionPerformed

    private void clearLogsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearLogsMenuItemActionPerformed
        try {
            File[] files = dopm_mm2Logdir.listFiles((dir, name) -> 
                    name.endsWith(".log") & !name.equals(dopm_mm2Logfile.getName()));
            for(File file : files){
                file.delete();
            }
        } catch (SecurityException e){
            dOPM_hostframeLogger.severe("Failed to delete logs "
                    + "(access denied probably) with: " + e.getMessage());
            throw e;
        } catch (Exception e){
            dOPM_hostframeLogger.severe("Failed to delete logs with: " + e.getMessage());
            throw e;
        }
    }//GEN-LAST:event_clearLogsMenuItemActionPerformed

    private void xyMaxSpeedCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xyMaxSpeedCheckBoxActionPerformed
        if (xyMaxSpeedCheckBox.isSelected()){
            deviceSettings.setUseMaxScanSpeedForXyStage(true);
            xyScanSpeedField.setEnabled(false);
        } else {
            deviceSettings.setUseMaxScanSpeedForXyStage(false);
            xyScanSpeedField.setEnabled(true);
        }
    }//GEN-LAST:event_xyMaxSpeedCheckBoxActionPerformed

    private void xyScanIntervalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xyScanIntervalFieldActionPerformed
        deviceSettings.setXyStageTriggerDistance(
            Double.parseDouble(xyScanIntervalField.getText()));
    }//GEN-LAST:event_xyScanIntervalFieldActionPerformed

    private void xyScanSpeedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xyScanSpeedFieldActionPerformed
        double scanSpeedInput = Double.parseDouble(xyScanSpeedField.getText());
        deviceSettings.setXyStageGlobalScanSpeed(scanSpeedInput);

        xyScanSpeedField.setText(String.format("%.4f",
            deviceSettings.getXyStageGlobalScanSpeed()));
    }//GEN-LAST:event_xyScanSpeedFieldActionPerformed

    private void xyScanLengthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xyScanLengthFieldActionPerformed
        double scanLength = Double.parseDouble(xyScanLengthField.getText());
        deviceSettings.setXyStageScanLength(scanLength);
    }//GEN-LAST:event_xyScanLengthFieldActionPerformed

    private void mirrorMaxSpeedCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mirrorMaxSpeedCheckBoxActionPerformed
        if (mirrorMaxSpeedCheckBox.isSelected()){
            deviceSettings.setUseMaxScanSpeedForMirror(true);
            mirrorScanSpeedField.setEnabled(false);
        } else {
            deviceSettings.setUseMaxScanSpeedForMirror(false);
            mirrorScanSpeedField.setEnabled(true);
        }
    }//GEN-LAST:event_mirrorMaxSpeedCheckBoxActionPerformed

    private void mirrorScanIntervalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mirrorScanIntervalFieldActionPerformed
        deviceSettings.setMirrorTriggerDistance(Double.parseDouble(mirrorScanIntervalField.getText()));
    }//GEN-LAST:event_mirrorScanIntervalFieldActionPerformed

    private void mirrorScanSpeedFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mirrorScanSpeedFieldActionPerformed
        double scanSpeedInput =
        Double.parseDouble(mirrorScanSpeedField.getText());

        // global scan speed setting
        deviceSettings.setMirrorStageGlobalScanSpeed(scanSpeedInput);
        mirrorScanSpeedField.setText(String.format("%.4f",
            deviceSettings.getMirrorStageGlobalScanSpeed()));
    }//GEN-LAST:event_mirrorScanSpeedFieldActionPerformed

    private void mirrorScanLengthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mirrorScanLengthFieldActionPerformed
        String scanLengthStr = mirrorScanLengthField.getText();
        double scanLength = Double.parseDouble(scanLengthStr);
        dOPM_hostframeLogger.info("parsing scan length as " + scanLengthStr);
        deviceSettings.setMirrorScanLength(scanLength);
    }//GEN-LAST:event_mirrorScanLengthFieldActionPerformed

    
    
    class typeVerifierDouble extends InputVerifier {
        @Override
        public boolean verify(JComponent input) {
            JTextField tf = (JTextField) input;
            try {
                Double.parseDouble(tf.getText());
                return true;
            } catch (Exception e) {
                dOPM_hostframeLogger.warning(e.getMessage());
                return false;
            }
        }
    } 

    class typeVerifier extends InputVerifier {
        String type;
        private typeVerifier(String type){
            this.type = type;
        }
        @Override
        public boolean verify(JComponent input) {
            JTextField tf = (JTextField) input;
            try {
                switch (type){
                case "double":
                    Double.parseDouble(tf.getText());
                    return true;
                case "int":
                    Integer.parseInt(tf.getText());
                    return true;
                case "string":
                    tf.getText(); // I mean, this is always a string.
                    return true;
                }
            } catch (Exception e) {
                dOPM_hostframeLogger.warning(String.format("invalid input for type %s. %s",
                        type, e.getMessage()));
                return false;
            }
            return false;
        }
    }

    public boolean isSaveImgToDisk() {
        return saveImgToDisk;
    }

    public void setSaveImgToDisk(boolean saveImgToDisk) {
        this.saveImgToDisk = saveImgToDisk;
    }

    public File getDefaultConfigFile() {
        return defaultConfigFile;
    }

    public void setDefaultConfigFile(File defaultConfigFile) {
        this.defaultConfigFile = defaultConfigFile;
    }

    public boolean isRunnableIsRunning() {
        return runnableIsRunning;
    }

    public void setRunnableIsRunning(boolean runnableIsRunning) {
        this.runnableIsRunning = runnableIsRunning;
    }
    
    
    public boolean getInterruptFlag() {
        return interruptFlag;
    }

    public void setInterruptFlag(boolean interruptFlag) {
        this.interruptFlag = interruptFlag;
    } 
    
    public File getBaseFolderDir() {
        return baseFolderDir;
    }

    public void setBaseFolderDir(File baseFolderDir) {
        this.baseFolderDir = baseFolderDir;
        setSettingsFolderDir(new File(baseFolderDir, "settings"));
        setDataFolderDir(new File(baseFolderDir, "data"));
    }

    public File getSettingsFolderDir() {
        return settingsFolderDir;
    }

    public void setSettingsFolderDir(File settingsFolderDir) {
        this.settingsFolderDir = settingsFolderDir;
    }

    public File getDataFolderDir() {
        return dataFolderDir;
    }

    public void setDataFolderDir(File dataFolderDir) {
        this.dataFolderDir = dataFolderDir;
    }

    public DeviceManager getDeviceSettings() {
        return deviceSettings;
    }

    public void setDeviceSettings(DeviceManager deviceSettings) {
        this.deviceSettings = deviceSettings;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            // TODO REPLACE util.logging.level with shorthand
            dOPM_hostframeLogger.log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            dOPM_hostframeLogger.log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            dOPM_hostframeLogger.log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            dOPM_hostframeLogger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dOPM_hostframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseDirectoryField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem clearLogsMenuItem;
    private javax.swing.JTextArea debugTextArea;
    private javax.swing.JPanel fileSettingsPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox mirrorMaxSpeedCheckBox;
    private javax.swing.JTextField mirrorScanIntervalField;
    private javax.swing.JTextField mirrorScanLengthField;
    private javax.swing.JRadioButton mirrorScanRadioButton;
    private javax.swing.JPanel mirrorScanSettingsPanel;
    private javax.swing.JTextField mirrorScanSpeedField;
    private javax.swing.JMenuItem openDeviceConfigMenuItem;
    private javax.swing.JTextField pcOfMaxField;
    private javax.swing.JTextField pcOfMaxField1;
    private javax.swing.JLabel pcOfMaxLabel;
    private javax.swing.JLabel pcOfMaxLabel1;
    private javax.swing.JTextField saveDirectoryField;
    private javax.swing.JLabel saveDirectoryLabel;
    private javax.swing.JCheckBox saveToDiskCheckBox;
    private javax.swing.JLabel scanIntervalLabel;
    private javax.swing.JLabel scanIntervalLabel1;
    private javax.swing.JLabel scanLengthLabel;
    private javax.swing.JLabel scanLengthLabel1;
    private javax.swing.JLabel scanSpeedLabel;
    private javax.swing.JLabel scanSpeedLabel1;
    private javax.swing.JLabel scanStageTypeLabel;
    private javax.swing.JButton snapTestButton;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JComboBox<String> triggerModeComboBox;
    private javax.swing.JLabel triggerModeLabel;
    private javax.swing.JCheckBox view1CheckBox;
    private javax.swing.JCheckBox view2CheckBox;
    private javax.swing.JLabel viewsLabel;
    private javax.swing.JRadioButton xScanRadioButton;
    private javax.swing.JCheckBox xyMaxSpeedCheckBox;
    private javax.swing.JTextField xyScanIntervalField;
    private javax.swing.JTextField xyScanLengthField;
    private javax.swing.JTextField xyScanSpeedField;
    private javax.swing.JPanel xyStageScanSettingsPanel;
    private javax.swing.JRadioButton yScanRadioButton;
    // End of variables declaration//GEN-END:variables
}
